In [54]:
#question 1
import numpy as np

oned = np.array([1,2,3])
twod = np.array([[1,2,3],[4,5,6],[7, 8, 9]])

print("la première liste:",oned.tolist())
print("la seconde liste:",twod.tolist())

la première liste: [1, 2, 3]
la seconde liste: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [71]:
#question 2
import numpy as np 
  
tab = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]]) 

print("La Matrice Numpy est:") 
print(tab) 

trace = np.trace(tab) 

print("\nle calcule de la somme des éléments diagonaux de la Matrice:") 
print(trace) 

La Matrice Numpy est:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

le calcule de la somme des éléments diagonaux de la Matrice:
176


In [72]:
#question 3
import numpy as np
a = np.array([[1, 2], [3, 5]])
print("le tableau est :")
print(a)
print("les valeurs supérieurs à x = 2 sont:",a[a>2])

le tableau est :
[[1 2]
 [3 5]]
les valeurs supérieurs à x = 2 sont: [3 5]


In [73]:
#question 4
import numpy as np
A = np.array([2, 3, 6])
B = np.array([4, 1, 7])
C = A + B
print("A=",A) 
print ("B=",B)
print ("la somme de A + B est egale à C=", C)

A= [2 3 6]
B= [4 1 7]
la somme de A + B est egale à C= [ 6  4 13]


In [74]:
#question 5
from statistics import mean 
  
list = [[3, 2, 5], [8, 4, 6], [3, 10, 7], [8, 6, 7]] 
  
print("La liste initiale : " + str(list)) 
  
res = [mean(idx) for idx in zip(*list)] 
  
res = mean(res) 
      
print("La Moyenne de la Matrice avec la fonction Mean : " + str(res))

La liste initiale : [[3, 2, 5], [8, 4, 6], [3, 10, 7], [8, 6, 7]]
La Moyenne de la Matrice avec la fonction Mean : 5.75
